export const AGENTS = [
  {
    id: "observer",
    label: "OBSERVER AGENT",
    count: 0,
    icon: "👁️",
    bg: "#eef3ff",
    carClass: "card-observer",
    borderColor: "#3b5bdb",
    numColor: "#3b5bdb",
  },
  {
    id: "rca",
    label: "RCA AGENT",
    count: 0,
    icon: "🔍",
    bg: "#fff8ee",
    carClass: "card-rca",
    borderColor: "#e67700",
    numColor: "#e67700",
  },
  {
    id: "decision",
    label: "DECISION AGENT",
    count: 0,
    icon: "🧠",
    bg: "#f9f0ff",
    carClass: "card-decision",
    borderColor: "#9c36b5",
    numColor: "#9c36b5",
  },
  {
    id: "selfhealing",
    label: "SELF-HEALING AGENT",
    count: 0,
    icon: "🔧",
    bg: "#f0fff4",
    carClass: "card-healing",
    borderColor: "#2f9e44",
    numColor: "#2f9e44",
  },
  {
    id: "dataquality",
    label: "DATA QUALITY AGENT",
    count: 0,
    icon: "✅",
    bg: "#f0fff4",
    carClass: "card-quality",
    borderColor: "#2f9e44",
    numColor: "#2f9e44",
  },
  {
    id: "selfservice",
    label: "SELF-SERVICE AGENT",
    count: 0,
    icon: "💬",
    bg: "#fff0f6",
    carClass: "card-selfservice",
    borderColor: "#c2255c",
    numColor: "#c2255c",
  },
  {
    id: "governance",
    label: "GOVERNANCE AGENT",
    count: 0,
    icon: "🛡️",
    bg: "#fff0f6",
    carClass: "card-governance",
    borderColor: "#c2255c",
    numColor: "#c2255c",
  },
  {
    id: "approval",
    label: "APPROVAL AGENT",
    count: 0,
    icon: "🧑‍⚖️",
    bg: "#f0fff4",
    carClass: "card-approval",
    borderColor: "#c22566",
    numColor: "#c2255c",
  },
];
